### ISSUE TITLE
Next.js example

### ISSUE THREAD

**Issue by talentlessguy** [lynxtaa/awesome-graphql-client#3]
Hello, would be cool to have a Next.js example in README showing how to combine clientside and server side fetching

**Comment by lynxtaa** [comment]
Hi! It's been a long since I've used Next.js. Do you have any examples how it can be done?

In react applications I'm using awesome-graphql-client in combination with [swr](https://www.npmjs.com/package/swr) for client-side caching and cache revalidation.

**Comment by talentlessguy** [comment]
@lynxtaa 

something to start with:

```ts
import React, { useState } from 'react'
import { NextPage } from 'next'

type Props = { initialData: ... }

const Page: NextPage<Props> = ({ initialData }) => {
  const [data, setData] = useState(initialData)

  useEffect(() => {
    // do something
    setData(...)
  }, [something])

  return ...
}

Page.getInitialProps = async ({ req, res }) => {
  // do something

  return { initialData }
}
```

**Comment by lynxtaa** [comment]
Solved in https://github.com/lynxtaa/awesome-graphql-client/pull/5
