### ISSUE TITLE
add the ability to change fetchOptions (or only headers) per request

### ISSUE THREAD

**Issue by robin-siegl** [lynxtaa/awesome-graphql-client#79]
**Is your feature request related to a problem? Please describe.**
Would be nice if you can setFetchOptions() (or only headers) per request.

**Describe the solution you'd like**
Setting some default headers in initial setup
```
const graphQlClient = new AwesomeGraphQLClient({
    endpoint: GRAPHQL_ENDPOINT,
    fetchOptions: {
          headers: {
            ...some default headers
        }
    }
});

// request with default headers/fetchOptions
graphQlClient.request(document, variables)
```

if some requests need an additional header
```
graphQlClient
    .setFetchOptions({
          headers: {
            ...additional headers
        }
    })
    .request(document, variables)
```

or only headers

```
graphQlClient
    .setHeaders({
        ...additional headers
    })
    .request(document, variables)
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lynxtaa** [comment]
Hello @robin-siegl , you could just use the third argument when calling the `.request(...)` method :)
