### ISSUE TITLE
Header Customization

### ISSUE THREAD

**Issue by milad2golnia** [lynxtaa/awesome-graphql-client#82]
**Is your feature request related to a problem? Please describe.**
It is common to have some authenticated urls which requires  a token in header to give you access to the desired resource.
Unfortunately I didn't see any way to set my preferred header variable for authorization.

**Describe the solution you'd like**
Provide a method to give user ability to set necessary headers. For example:
```
client.setHeader({
     variable: value
})
```

**Comment by robin-siegl** [comment]
@milad2golnia what you can do right now is:

```
awesomeGraphQLClient.setFetchOptions({
    headers: {
        variable: value
    },
});
```

but this will set the headers on the `awesomeGraphQLClient` not only to the current request.
I already opened a issue, because this is would make things easier for me.
See: https://github.com/lynxtaa/awesome-graphql-client/issues/79
