### ISSUE TITLE
Support for a custom appendFile function to be configured

### ISSUE THREAD

**Issue by strongpauly** [lynxtaa/awesome-graphql-client#93]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to customise how the objects I determine to be files are appended to the FormData instance.

**Describe the solution you'd like**
When the AwesomeGraphQLClient instance is created, pass an optional custom `appendFile` function that can be used as an escape hatch to append the file to the form

**Describe alternatives you've considered**
I would like this so I can set the file name on the form.  Uncertain of how to do this otherwise.

**Additional context**
Libraries such as https://www.npmjs.com/package/apollo-upload-client allow for such an option.

**Comment by lynxtaa** [comment]
Hi @strongpauly !

> so I can set the file name on the form

A `File` instances are supported so you could control the filename when creating a File:
```ts
const client = new AwesomeGraphQLClient({
  endpoint: '...',
})
await client.request(..., { file: new File([blob], 'my-filename.png') })
```

Could you please provide more details since I'm not sure about the use case?

**Comment by lynxtaa** [comment]
And if you're uploading a file from browser's `<input type='file' />`:

```ts
const client = new AwesomeGraphQLClient({
  endpoint: '...',
})
const file = document.querySelector('input#avatar').files[0]
await client.request(..., { file: new File([file], 'my-filename.png') })
```

**Comment by strongpauly** [comment]
> Hi @strongpauly !
> 
> > so I can set the file name on the form
> 
> A `File` instances are supported so you could control the filename when creating a File:
> 
> ```ts
> const client = new AwesomeGraphQLClient({
>   endpoint: '...',
> })
> await client.request(..., { file: new File([blob], 'my-filename.png') })
> ```
> 
> Could you please provide more details since I'm not sure about the use case

This would support my use case, if this implementation streams the binary data under the hood.  I'm implementing a server that needs to stream a file upload to an upstream service.  I'm trying to avoid loading the whole file in memory while this is happening.

**Comment by lynxtaa** [comment]
Yes, it will be a stream.

If you're using `awesome-graphql-client` on browser then a blob from a form input would be streamable by default.

And for NodeJS we have examples for NodeJS 18 and NodeJS >= 20 in https://github.com/lynxtaa/awesome-graphql-client/blob/master/README.md and both are streamable

**Comment by strongpauly** [comment]
Ok thanks.  Seems like I can achieve my goals without this feature.  Thanks again for your help.
